<template><div><h1 id="vue开发案例" tabindex="-1"><a class="header-anchor" href="#vue开发案例" aria-hidden="true">#</a> vue开发案例</h1>
<h2 id="一、实现六边形进度条环绕动画效果" tabindex="-1"><a class="header-anchor" href="#一、实现六边形进度条环绕动画效果" aria-hidden="true">#</a> 一、实现六边形进度条环绕动画效果</h2>
<h3 id="clip-path属性实现六边形" tabindex="-1"><a class="header-anchor" href="#clip-path属性实现六边形" aria-hidden="true">#</a> clip-path属性实现六边形</h3>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>import-icon gradient-border<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>animation<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>icon2<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>重要<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>br</span><span class="token punctuation">></span></span>提醒<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-css ext-css line-numbers-mode"><pre v-pre class="language-css"><code><span class="token comment">/** 六边形背景 **/</span>
<span class="token selector">.import-tip .import-icon</span> <span class="token punctuation">{</span>
    <span class="token property">position</span><span class="token punctuation">:</span> relative<span class="token punctuation">;</span>
    <span class="token property">box-sizing</span><span class="token punctuation">:</span> border-box<span class="token punctuation">;</span>
    <span class="token property">display</span><span class="token punctuation">:</span> flex<span class="token punctuation">;</span>
    <span class="token property">justify-content</span><span class="token punctuation">:</span> center<span class="token punctuation">;</span>
    <span class="token property">align-items</span><span class="token punctuation">:</span> center<span class="token punctuation">;</span>
    <span class="token property">margin</span><span class="token punctuation">:</span> 0 20px 0 40px<span class="token punctuation">;</span>
    <span class="token property">background-color</span><span class="token punctuation">:</span> <span class="token function">rgba</span><span class="token punctuation">(</span>244<span class="token punctuation">,</span> 151<span class="token punctuation">,</span> 20<span class="token punctuation">,</span> 0.2<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token property">font-size</span><span class="token punctuation">:</span> 36px<span class="token punctuation">;</span>
    <span class="token property">font-weight</span><span class="token punctuation">:</span> bold<span class="token punctuation">;</span>
    <span class="token property">color</span><span class="token punctuation">:</span> #ffffff<span class="token punctuation">;</span>
    <span class="token property">width</span><span class="token punctuation">:</span> 169px<span class="token punctuation">;</span>
    <span class="token property">height</span><span class="token punctuation">:</span> 196px<span class="token punctuation">;</span>
    <span class="token property">clip-path</span><span class="token punctuation">:</span> <span class="token function">polygon</span><span class="token punctuation">(</span>
            0 25%<span class="token punctuation">,</span>
            50% 0<span class="token punctuation">,</span>
            100% 25%<span class="token punctuation">,</span>
            100% 75%<span class="token punctuation">,</span>
            50% 100%<span class="token punctuation">,</span>
            0 75%
    <span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token comment">/** 六边形顶层 **/</span>
<span class="token selector">.import-icon .icon2</span> <span class="token punctuation">{</span>
    <span class="token property">text-align</span><span class="token punctuation">:</span> center<span class="token punctuation">;</span>
    <span class="token property">line-height</span><span class="token punctuation">:</span> 40px<span class="token punctuation">;</span>
    <span class="token property">display</span><span class="token punctuation">:</span> flex<span class="token punctuation">;</span>
    <span class="token property">align-items</span><span class="token punctuation">:</span> center<span class="token punctuation">;</span>
    <span class="token property">justify-content</span><span class="token punctuation">:</span> center<span class="token punctuation">;</span>
    <span class="token property">width</span><span class="token punctuation">:</span> 152px<span class="token punctuation">;</span>
    <span class="token property">height</span><span class="token punctuation">:</span> 176px<span class="token punctuation">;</span>
    <span class="token property">background-color</span><span class="token punctuation">:</span> #f49714<span class="token punctuation">;</span>
    <span class="token property">clip-path</span><span class="token punctuation">:</span> <span class="token function">polygon</span><span class="token punctuation">(</span>
            0 25%<span class="token punctuation">,</span>
            50% 0<span class="token punctuation">,</span>
            100% 25%<span class="token punctuation">,</span>
            100% 75%<span class="token punctuation">,</span>
            50% 100%<span class="token punctuation">,</span>
            0 75%
    <span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token comment">/** 三角形旋转层 **/</span>
<span class="token selector">.import-icon .animation</span> <span class="token punctuation">{</span>
    <span class="token property">width</span><span class="token punctuation">:</span> 100px<span class="token punctuation">;</span>
    <span class="token property">height</span><span class="token punctuation">:</span> 100px<span class="token punctuation">;</span>
    <span class="token property">background-image</span><span class="token punctuation">:</span> <span class="token function">linear-gradient</span><span class="token punctuation">(</span>-90deg<span class="token punctuation">,</span>
    <span class="token function">rgba</span><span class="token punctuation">(</span>255<span class="token punctuation">,</span> 180<span class="token punctuation">,</span> 109<span class="token punctuation">,</span> 0.11<span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token function">rgba</span><span class="token punctuation">(</span>255<span class="token punctuation">,</span> 123<span class="token punctuation">,</span> 0<span class="token punctuation">,</span> 0.41<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token property">border-radius</span><span class="token punctuation">:</span> 50%<span class="token punctuation">;</span>
    <span class="token property">clip-path</span><span class="token punctuation">:</span> <span class="token function">polygon</span><span class="token punctuation">(</span>50% 0%<span class="token punctuation">,</span> 0% 100%<span class="token punctuation">,</span> 100% 100%<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token property">position</span><span class="token punctuation">:</span> absolute<span class="token punctuation">;</span>
    <span class="token property">top</span><span class="token punctuation">:</span> 98px<span class="token punctuation">;</span>
    <span class="token property">left</span><span class="token punctuation">:</span> 36px<span class="token punctuation">;</span>
    <span class="token property">animation</span><span class="token punctuation">:</span> loading 1.5s linear infinite<span class="token punctuation">;</span>
    <span class="token property">transform-origin</span><span class="token punctuation">:</span> 50px 0<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token comment">/** 动画 **/</span>
<span class="token atrule"><span class="token rule">@keyframes</span> loading</span> <span class="token punctuation">{</span>
    <span class="token selector">0%</span> <span class="token punctuation">{</span>
        <span class="token property">transform</span><span class="token punctuation">:</span> <span class="token function">rotate</span><span class="token punctuation">(</span>0deg<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token selector">100%</span> <span class="token punctuation">{</span>
        <span class="token property">transform</span><span class="token punctuation">:</span> <span class="token function">rotate</span><span class="token punctuation">(</span>360deg<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="二、h5调起app以及适配问题" tabindex="-1"><a class="header-anchor" href="#二、h5调起app以及适配问题" aria-hidden="true">#</a> 二、H5调起APP以及适配问题</h2>
<h3 id="调起水滴app代码示例" tabindex="-1"><a class="header-anchor" href="#调起水滴app代码示例" aria-hidden="true">#</a> 调起水滴APP代码示例</h3>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token doc-comment comment">/**
 * 下载水滴app
 * ios使用Universal Link，安卓使用URL Scheme
 */</span>
 <span class="token keyword">function</span> <span class="token function">uploadApp</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
  <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">addRecord</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>navigator<span class="token punctuation">.</span>userAgent<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(iPhone|iPod|iPad);?</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> loadDateTime <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    window<span class="token punctuation">.</span><span class="token function">setTimeout</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">var</span> timeOutDateTime <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span>timeOutDateTime <span class="token operator">-</span> loadDateTime <span class="token operator">&lt;</span> <span class="token number">5000</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        window<span class="token punctuation">.</span>location <span class="token operator">=</span>
            <span class="token string">"https://itunes.apple.com/us/app/%E6%B0%B4%E6%BB%B4%E4%BF%A1%E7%94%A8/id1075736286?l=zh&amp;ls=1&amp;mt=8"</span><span class="token punctuation">;</span> <span class="token comment">//ios下载地址</span>
      <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
        window<span class="token punctuation">.</span><span class="token function">close</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token number">1500</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    window<span class="token punctuation">.</span>location <span class="token operator">=</span> <span class="token string">"https://shuidi.cn/ulink/"</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>navigator<span class="token punctuation">.</span>userAgent<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">android</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">try</span> <span class="token punctuation">{</span>
      window<span class="token punctuation">.</span>location <span class="token operator">=</span> <span class="token string">"shuidi://"</span><span class="token punctuation">;</span>
      <span class="token function">setTimeout</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        window<span class="token punctuation">.</span>location <span class="token operator">=</span>
            <span class="token string">"https://filecdn.shuidi.cn/file/upload/files/38/7c/62/20/387c62205938acda32e9690d946a486d.apk/%E6%B0%B4%E6%BB%B4%E4%BF%A1%E7%94%A8.version.153(3).apk"</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token number">500</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span>e<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="三、vue高德地图js-api-应用" tabindex="-1"><a class="header-anchor" href="#三、vue高德地图js-api-应用" aria-hidden="true">#</a> 三、vue高德地图js api 应用</h2>
<h3 id="引入方法" tabindex="-1"><a class="header-anchor" href="#引入方法" aria-hidden="true">#</a> 引入方法</h3>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>page<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>container<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>map-tip<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>地图搜索精准定位<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-css ext-css line-numbers-mode"><pre v-pre class="language-css"><code><span class="token selector">.page</span><span class="token punctuation">{</span>
  <span class="token property">font-weight</span><span class="token punctuation">:</span> normal<span class="token punctuation">;</span>
  <span class="token property">letter-spacing</span><span class="token punctuation">:</span> 0<span class="token punctuation">;</span>
  <span class="token property">overflow-x</span><span class="token punctuation">:</span> hidden<span class="token punctuation">;</span>
  <span class="token property">overflow-y</span><span class="token punctuation">:</span> auto<span class="token punctuation">;</span>
  <span class="token property">-webkit-overflow-scrolling</span><span class="token punctuation">:</span> touch<span class="token punctuation">;</span>
  <span class="token property">height</span><span class="token punctuation">:</span> 100vh<span class="token punctuation">;</span>
  <span class="token property">background-color</span><span class="token punctuation">:</span> #f4f4f4<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token selector">#container</span><span class="token punctuation">{</span>
  <span class="token property">height</span><span class="token punctuation">:</span> 100vh<span class="token punctuation">;</span>
  <span class="token property">width</span><span class="token punctuation">:</span> 100%
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token comment">// npm install amap-jsapi-loader --save</span>
<span class="token keyword">import</span> AMapLoader <span class="token keyword">from</span> <span class="token string">'@amap/amap-jsapi-loader'</span><span class="token punctuation">;</span>

<span class="token keyword">this</span><span class="token punctuation">.</span>geo <span class="token operator">=</span><span class="token string">'116.39, 39.9'</span>

<span class="token doc-comment comment">/**
 * 高德地图初始化
 */</span>
<span class="token keyword">function</span> <span class="token function">initMap</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
  AMapLoader<span class="token punctuation">.</span><span class="token function">load</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    key<span class="token operator">:</span><span class="token string">"46b438232abd32f4e5bc4a3dd8e8f85d"</span><span class="token punctuation">,</span> 
    <span class="token comment">// 申请好的Web端开发者Key，首次调用 load 时必填</span>
    version<span class="token operator">:</span><span class="token string">"2.0"</span><span class="token punctuation">,</span>      <span class="token comment">// 指定要加载的 JSAPI 的版本，缺省时默认为 1.4.15</span>
    plugins<span class="token operator">:</span><span class="token punctuation">[</span><span class="token string">''</span><span class="token punctuation">]</span><span class="token punctuation">,</span>       <span class="token comment">// 需要使用的的插件列表，如比例尺'AMap.Scale'等</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span>AMap<span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>map <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">AMap</span><span class="token punctuation">.</span><span class="token function">Map</span><span class="token punctuation">(</span><span class="token string">"container"</span><span class="token punctuation">,</span><span class="token punctuation">{</span>  <span class="token comment">//设置地图容器id</span>
      viewMode<span class="token operator">:</span><span class="token string">"3D"</span><span class="token punctuation">,</span>    <span class="token comment">//是否为3D地图模式</span>
      zoom<span class="token operator">:</span><span class="token number">16</span><span class="token punctuation">,</span>           <span class="token comment">//初始化地图级别</span>
      center<span class="token operator">:</span><span class="token punctuation">[</span><span class="token operator">+</span><span class="token keyword">this</span><span class="token punctuation">.</span>geo<span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span><span class="token string">','</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token operator">+</span><span class="token keyword">this</span><span class="token punctuation">.</span>geo<span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span><span class="token string">','</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">]</span><span class="token punctuation">,</span> 
      <span class="token comment">//初始化地图中心点位置</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> marker <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">AMap</span><span class="token punctuation">.</span><span class="token function">Marker</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      position<span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">AMap</span><span class="token punctuation">.</span><span class="token function">LngLat</span><span class="token punctuation">(</span><span class="token number">116.39</span><span class="token punctuation">,</span> <span class="token number">39.9</span><span class="token punctuation">)</span><span class="token punctuation">,</span> 
      <span class="token comment">// 经纬度对象，也可以是经纬度构成的一维数组[116.39, 39.9]</span>
      title<span class="token operator">:</span> <span class="token string">'北京'</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>map<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span>marker<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span>e<span class="token operator">=></span><span class="token punctuation">{</span>
    <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>e<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="自定义标注点-传入图片" tabindex="-1"><a class="header-anchor" href="#自定义标注点-传入图片" aria-hidden="true">#</a> 自定义标注点，传入图片</h3>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">const</span> marker <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">AMap</span><span class="token punctuation">.</span><span class="token function">Marker</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  position<span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">AMap</span><span class="token punctuation">.</span><span class="token function">LngLat</span><span class="token punctuation">(</span><span class="token operator">+</span><span class="token keyword">this</span><span class="token punctuation">.</span>location<span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span><span class="token string">','</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token operator">+</span><span class="token keyword">this</span><span class="token punctuation">.</span>location<span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span><span class="token string">','</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
  <span class="token comment">// position: [116.39, 39.9],</span>
  offset<span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">AMap</span><span class="token punctuation">.</span><span class="token function">Pixel</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token comment">// 设置点标记偏移量</span>
  anchor<span class="token operator">:</span><span class="token string">'bottom-center'</span><span class="token punctuation">,</span> <span class="token comment">// 设置锚点方位</span>
  icon<span class="token operator">:</span> <span class="token string">'https://staticcdn.shuidi.cn/shuidi/images/map/location-icon.png'</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="自定义拖拽选点组件" tabindex="-1"><a class="header-anchor" href="#自定义拖拽选点组件" aria-hidden="true">#</a> 自定义拖拽选点组件</h3>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token operator">&lt;</span><span class="token operator">!</span><span class="token operator">--</span>aMapUIjs 引入<span class="token operator">--</span><span class="token operator">></span>
<span class="token comment">// &lt;script src="//webapi.amap.com/ui/1.0/main.js">&lt;/script></span>


<span class="token doc-comment comment">/**
 * 地图拖拽组件初始化
 */</span>
<span class="token keyword">function</span> <span class="token function">positionPicker</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
   window<span class="token punctuation">.</span>_AMapSecurityConfig <span class="token operator">=</span> <span class="token punctuation">{</span>
  securityJsCode<span class="token operator">:</span><span class="token string">'ef7ee93fe0ce14c3dae22a2d3e9ae843'</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span>
  <span class="token keyword">let</span> that <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">;</span>
  <span class="token comment">// 加载地图js</span>
  AMapLoader<span class="token punctuation">.</span><span class="token function">load</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    key<span class="token operator">:</span> <span class="token string">"010bac8f887bf63ff0d0d5c71b29e4bb"</span><span class="token punctuation">,</span>
    version<span class="token operator">:</span><span class="token string">"2.0"</span><span class="token punctuation">,</span>
    plugins<span class="token operator">:</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    AMapUI<span class="token operator">:</span> <span class="token punctuation">{</span>
      version<span class="token operator">:</span> <span class="token string">'1.1'</span><span class="token punctuation">,</span>
      plugins<span class="token operator">:</span><span class="token punctuation">[</span><span class="token string">'misc/PositionPicker'</span><span class="token punctuation">]</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span>AMap<span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span>
    <span class="token comment">// 拖拽地图组件</span>
    AMapUI<span class="token punctuation">.</span><span class="token function">loadUI</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">"misc/PositionPicker"</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span>PositionPicker<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">const</span> map <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">AMap</span><span class="token punctuation">.</span><span class="token function">Map</span><span class="token punctuation">(</span><span class="token string">"container"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span>
        zoom<span class="token operator">:</span> <span class="token number">16</span><span class="token punctuation">,</span>
        center<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token operator">+</span>that<span class="token punctuation">.</span>location<span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span><span class="token string">','</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token operator">+</span>that<span class="token punctuation">.</span>location<span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span><span class="token string">','</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">const</span> positionPicker <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">PositionPicker</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
        mode<span class="token operator">:</span> <span class="token string">"dragMap"</span><span class="token punctuation">,</span>
        map<span class="token operator">:</span> map<span class="token punctuation">,</span>
        <span class="token comment">// center: [116.39, 39.9],</span>
        center<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token operator">+</span>that<span class="token punctuation">.</span>location<span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span><span class="token string">','</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token operator">+</span>that<span class="token punctuation">.</span>location<span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span><span class="token string">','</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
        iconStyle<span class="token operator">:</span><span class="token punctuation">{</span>  <span class="token comment">// 自定义标注点样式</span>
          url<span class="token operator">:</span><span class="token string">'https://staticcdn.shuidi.cn/shuidi/images/map/location-icon2.png'</span><span class="token punctuation">,</span><span class="token comment">//图片地址</span>
          <span class="token comment">// url:'http://static.test.pingansec.com/shuidi/images/map/location-icon2.png',//图片地址</span>
          size<span class="token operator">:</span><span class="token punctuation">[</span><span class="token number">50</span><span class="token punctuation">,</span><span class="token number">50</span><span class="token punctuation">]</span><span class="token punctuation">,</span>  <span class="token comment">//要显示的点大小，将缩放图片</span>
          ancher<span class="token operator">:</span><span class="token punctuation">[</span><span class="token number">25</span><span class="token punctuation">,</span><span class="token number">52</span><span class="token punctuation">]</span><span class="token punctuation">,</span><span class="token comment">// 锚点的位置，即被size缩放之后，图片的什么位置作为选中的位置</span>
        <span class="token punctuation">}</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      positionPicker<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">"success"</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span>positionResult<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        that<span class="token punctuation">.</span>mapDragNum<span class="token operator">++</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span><span class="token punctuation">(</span> that<span class="token punctuation">.</span>mapDragNum <span class="token operator">></span> <span class="token number">2</span> <span class="token punctuation">)</span><span class="token punctuation">{</span>
          that<span class="token punctuation">.</span><span class="token function">smsClick</span><span class="token punctuation">(</span><span class="token string">'click_6'</span><span class="token punctuation">)</span> <span class="token comment">// 是否拖拽地图</span>
        <span class="token punctuation">}</span>
        <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>positionResult<span class="token punctuation">.</span>position<span class="token punctuation">.</span>lng<span class="token punctuation">,</span> positionResult<span class="token punctuation">.</span>position<span class="token punctuation">.</span>lat<span class="token punctuation">)</span>
        <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>positionResult<span class="token punctuation">.</span>address<span class="token punctuation">)</span>
        that<span class="token punctuation">.</span>address <span class="token operator">=</span> positionResult<span class="token punctuation">.</span>address<span class="token punctuation">;</span>
        that<span class="token punctuation">.</span>location <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>positionResult<span class="token punctuation">.</span>position<span class="token punctuation">.</span>lng<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">,</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>positionResult<span class="token punctuation">.</span>position<span class="token punctuation">.</span>lat<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      positionPicker<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">"fail"</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span>positionResult<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">定位失败:</span><span class="token template-punctuation string">`</span></span> <span class="token operator">+</span> positionResult<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      positionPicker<span class="token punctuation">.</span><span class="token function">start</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      map<span class="token punctuation">.</span><span class="token function">panBy</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
